config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'edit_profile', to: "devise/registrations#edit"
  end

  get 'my_profile', to: "pages#my_profile"
  get 'contact_us', to: "pages#contact_us"

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :contracts
  get "dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_many :contracts, through: :products
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :products
  # has_many :contracts, through: :products
  has_one_attached :logo
end

app/models/contract.rb
class Contract < ApplicationRecord
  has_one_attached :pdf_contract
  has_one_attached :pdf_certificate

  belongs_to :user
  belongs_to :product
  belongs_to :company

  validates :company_id, presence: true
  validates :product_id, presence: true
  validates :starts_at, presence: true

  has_many :coverages
  enum :source, { personal: 0, work: 1 }

  include PgSearch::Model
  pg_search_scope :search_by_company_and_product,
  # against: [ :title, :synopsis ],
  associated_against: {
    company: [:name],
    product: [:name],
  },
  using: {
    tsearch: { prefix: true }
  }

  delegate :category, to: :product
  delegate :company, to: :product

  # TIMINGS = ["Monthly", "Annually", "Specific Period"]
end

app/models/coverage.rb
class Coverage < ApplicationRecord
  belongs_to :contract
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  belongs_to :category

  has_many :contracts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contracts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def after_sign_up_path(resource)
    dashboard_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def user_root_path
    my_profile_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender, :phone_number, :address, :family_status, :birth_date])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :gender, :phone_number, :address, :family_status, :birth_date])
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].present?
      @contracts = policy_scope(Contract).joins(
        "INNER JOIN products ON products.id = contracts.product_id
        JOIN categories ON categories.id = products.category_id
        AND categories.name = '#{params[:category]}'"
      )
    else
      @contracts = policy_scope(Contract)
    end

    @contracts = @contracts.search_by_company_and_product(params[:query]) if params[:query].present?
    @contracts.order!(active: :desc)
  end

  def show
    @coverqge = Coverage.find_by(contract: @contract)
    authorize @contract
  end

  def new
    @contract = Contract.new
    @company_products = Hash.new
    Company.all.each do |company|

      comp_products = Hash.new
      company.products.each do |product|
        comp_products["#{product.id}"] = product.name
      end

      @company_products["#{company.id}"] = comp_products
    end

    authorize @contract
  end

  def create
    @contract = Contract.new(contract_params)
    @contract.user = current_user

    authorize @contract

    if @contract.save
      redirect_to contracts_path(category: @contract.product.category.name)
    else
      render :new
    end
  end

  def edit
    authorize @contract
  end

  def update
   @contract = Contract.find_by(id: params[:id])
    if @contract.update(contract_params)
      redirect_to contract_path(@contract.id), notice: "Contract was updated"
    else
      render :edit
    end
   authorize @contract
  end

  def destroy
    @contract.destroy
    redirect_to contracts_path(category: @contract.product.category.name), status: :see_other

    authorize @contract
  end

  private

  def contract_params
    params.require(:contract).permit(
      :price, :source, :starts_at, :ends_at, :status, :created_at,
      :updated_at, :pdf_contract, :pdf_certificate,
      :company_id, :product_id, :active, :timing
    )
  end

  def set_contract
    @contract = Contract.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @resource = User.new
  end

  def dashboard
    @categories = Category.all
  end

  def my_profile
    current_user.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/edit.html.erb
<div class="panel panel-default">
    <div class="container-fluid gradient">
      <div class="container panel-default">
      <h1>Edit your contract - <%= @contract.product.name %></h1>
      </div>
    </div>
    <div class="panel-body">
      <div class="container">
        <div class="row" data-controller="form-display">
            <%= simple_form_for @contract, data: {turbo: false},
            class:"position-relative" do |f| %>
              <%= f.association :company %>
              <%= f.association :product %>
              <%= f.input :source,
                          input_html: {
                            class: "form-rounded",
                            data: {
                              form_display_target: "source",
                              action:"change->form-display#showInputs"
                            }
                          },
                          as: :select,
                          include_blank: false,
                          collection: Contract.sources.keys %>
              <%= f.input :price,
                          input_html: {
                            class: "form-rounded"
                          },
                          wrapper_html: {
                            data: { form_display_target: "input" }
                          },
                          as: :integer %>
              <%= f.input :timing,
                          label: "Payment frequency",
                          as: :radio_buttons,
                          checked: @contract.timing,
                          collection_wrapper_tag: "div",
                          collection_wrapper_class: "timing-wrapper",
                          item_wrapper_class: "timing-item",
                          input_html: {
                            class: "timing-selector"
                          },
                          wrapper_html: {
                            data: { form_display_target: "input" }
                          },
                          collection: ["Monthly", "Annually", "Specific Timing"],
                          checked: @contract.timing %>
              <%= f.input :active,
                          checked: true,
                          as: :radio_buttons,
                          label: "Insurance active?",
                          checked: @contract.active,
                          wrapper_html: {
                            data: { form_display_target: "input" }
                          }
                          %>
              <div class="d-flex mb-3">
                <div>
                  Starts at:
                  <%= f.date_field :starts_at,
                                    class: "form-rounded form-control",
                                    as: :date,
                                    data: {
                                      change_color_target:"input",
                                      action:"change->change-color#update"
                                    }%>
                </div>
                <div>
                  Ends at:
                  <%= f.date_field :ends_at,
                                    class: "form-rounded form-control",
                                    as: :date,
                                    data: {
                                      change_color_target:"input",
                                      action:"change->change-color#update"
                                    }%>
                </div>
              </div>
              <%= f.input :pdf_contract,
                          as: :file %>
              <%= f.input :pdf_certificate,
                          as: :file %>
              <div class="d-flex gapp" style="flex-direction: column">
              <%= f.button :button,
                          class: 'btn-grad-light' %>
              <%= link_to "Back", contract_path(@contract.id), class:"btn-gray", style:"width: 200px;" %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/contracts/index.html.erb
<div class="container-fluid gradient">
  <div class="container panel-default">
    <h1>My contracts</h1>
  </div>
</div>
<div class="container">
  <div class="d-flex", style= "justify-content: space-between">
         <%= link_to "Back", "/dashboard", class:"btn-gray", style:"width: 243px; margin-top: 20px;" %>
         <%= link_to "New Contract", new_contract_path, class: "btn btn-grad-light", style:"padding-top: 15px;"%>
  </div>
  <div class="nav-search mt-4">
    <div class="search">
      <%= form_with url: contracts_path, method: :get, class: "d-flex gap" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Look for a Contract"
        %>
        <%= hidden_field_tag :category, params[:category] %>
        <%= button_tag "Search", class: "btn-gray" %>
      <% end %>
    </div>
      <% @contracts.each do |contract| %>
        <%if contract.ends_at %>
          <% contract_duration = ((contract.ends_at&.to_time&.to_i - contract.starts_at.to_time.to_i) / 3600 / 24) %>
        <% else %>
          <% contract_duration = 0 %>
        <% end %>
          <div class="row insurance-card insurance-card-hover p-3">
            <div class="col-3">
              <div class="logo">
                <%= cl_image_tag contract.company.logo.key, class:"insurance-logo", style: "width: 100%; background: white" %>
              </div>
            </div>

            <div class="col-5">
              <h1><strong><%= contract.product.category.name %> - <%= contract.product.name %></strong></h1>
              <h2><strong><%= contract.product.company.name %></strong></h2>
              <% if contract.source === "work" %>
                <h2><%= "No cost" %></h2>
              <% elsif contract.timing === "Monthly" %>
                <h2><%= contract.price %> €/month</h2>
              <% elsif contract.timing === "Annually" %>
                <h2><%= contract.price %> €/year</h2>
              <% elsif contract_duration > 365 %>
                <h2><%= contract.price %> € for <%= contract_duration / 365 %> year(s)</h2>
              <% elsif contract_duration > 30 %>
                <h2><%= contract.price %> € for <%= contract_duration / 30 %> month(s)</h2>
              <% elsif contract_duration > 0 %>
                <h2><%= contract.price %> € for <%= contract_duration %> day(s)</h2>
              <% else %>
                <h2><%= contract.price %> €</h2>

              <% end %>
              <div class="d-flex" style="margin: 40px 0px;">
                  <%= link_to "", contract_path(contract), class:"fa-solid fa-magnifying-glass" %>
                  <%= link_to "", edit_contract_path(contract), class:"fa-solid fa-file-pen", style:"margin:0px 50px" %>
                  <%= link_to "", contract_path(contract),  class:"fa-solid fa-trash",
                                                            data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this contract?"} %>

              </div>
            </div>

            <div class="col-4">
              <div class="row">
                <div class="col-6 border-bottom pt-2">
                  <h2>Status: </h2>
                </div>
                <div class="col-6 border-bottom pt-2 centered">
                  <% if contract.active %>
                    <h2 class="pink" style="text-align: center;"><strong>Active</strong></h2>
                  <% else %>
                    <h2 class="gray", style="text-align: center;"><strong>Inactive</strong></h2>
                  <% end %>
                </div>
                <div class="col-6 border-bottom pt-2">
                  <h2>Starts at:</h2>
                </div>
                <div class="col-6 border-bottom pt-2 centered" style="text-align: center;">
                  <h2><strong><%= contract.starts_at.strftime('%d %b %Y') %></strong></h2>
                </div>
                <div class="col-6 border-bottom pt-2">
                  <h2>Ends at:</h2>
                </div>
                <div class="col-6 border-bottom pt-2 centered" style="text-align: center;">
                  <h2><strong><%= contract.ends_at&.strftime('%d %b %Y') %></strong></h2>
                </div>
                <div class="col-6 border-bottom pt-2">
                  <h2>Contract source:</h2>
                </div>
                <div class="col-6 border-bottom pt-2 centered" style="text-align: center;">
                  <h2><strong><%= contract.source.capitalize %></strong></h2>
                </div>
                <% unless contract.pdf_contract.attached? %>
                  <h4><i class="fa-solid fa-triangle-exclamation"></i> No pdf contract</h4>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  <br>
</div>

app/views/contracts/new.html.erb
<div class="panel panel-default">
    <div class="container-fluid gradient">
      <div class="container panel-default">
        <h1>Create your contract</h1>
      </div>
    </div>
    <div class="panel-body">
      <div class="container">
        <div class="row" data-controller="form-display company-products" data-company-products-hash-value="<%= @company_products %>">
            <%= simple_form_for @contract, data: {turbo: false}, class:"position-relative" do |f| %>
              <%= f.association :company,
                                label: "Insurer name",
                                include_blank: false,
                                include_hidden: false,
                                input_html: {
                                  class: "form-rounded",
                                  data: {
                                    change_color_target: "input",
                                    action: "change->company-products#updateProducts"
                                  }
                                },
                                label: "Company name" %>
              <%= f.association :product,
                                include_blank: false,
                                include_hidden: false,
                                input_html: {
                                  class: "form-rounded",
                                  data: {
                                    company_products_target: "product"
                                  }
                                },
                                label: "Product name",
                                data: {
                                  change_color_target:"input",
                                  action:"change->change-color#update"
                                }%>
              <%= f.input :source,
                          input_html: {
                            class: "form-rounded",
                            data: {
                              form_display_target: "source",
                              action:"change->form-display#showInputs"
                            }
                          },
                          as: :select,
                          include_blank: false,
                          include_hidden: false,
                          collection: Contract.sources.keys %>
              <%= f.input :price,
                          input_html: {
                            class: "form-rounded"
                          },
                          wrapper_html: {
                            data: { form_display_target: "input" }
                          },
                          as: :integer %>
              <%= f.input :timing,
                          label: "Payment frequency",
                          as: :radio_buttons,
                          collection_wrapper_tag: "div",
                          collection_wrapper_class: "timing-wrapper",
                          item_wrapper_class: "timing-item",
                          input_html: {
                            class: "timing-selector"
                          },
                          wrapper_html: {
                            data: { form_display_target: "input" }
                          },
                          collection: ["Monthly", "Annually", "Specific Period"] %>
              <%= f.input :active,
                          checked: true,
                          as: :radio_buttons,
                          label: "Insurance active?",
                          wrapper_html: {
                            data: { form_display_target: "input" }
                          } %>
              <div class="d-flex mb-3">
                <div>
                  Starts at:
                  <%= f.date_field :starts_at,
                                    class: "form-rounded form-control",
                                    as: :date,
                                    data: {
                                      change_color_target:"input",
                                      action:"change->change-color#update"
                                    }%>
                </div>
                <div>
                  Ends at:
                  <%= f.date_field :ends_at,
                                    class: "form-rounded form-control",
                                    as: :date,
                                    data: {
                                      change_color_target:"input",
                                      action:"change->change-color#update"
                                    }%>
                </div>
              </div>
              <%= f.input :pdf_contract,
                          input_html: {
                            class: "form-rounded"
                          },
                          as: :file,
                          data: {
                            change_color_target:"input",
                            action:"change->change-color#update"
                          }%>
              <%= f.input :pdf_certificate,
                          input_html: {
                            class: "form-rounded"
                          },
                          as: :file,
                          data: {
                            change_color_target:"input",
                            action:"change->change-color#update"
                          }%>
              <div class="d-flex gapp" style="flex-direction: column">
              <%= f.button :button,
                            class: 'btn-grad-light' %>
              <%= link_to "Back", contracts_path, class:"btn-gray", style:"width: 200px;" %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/contracts/show.html.erb
<div class="container-fluid gradient">
  <div class="container panel-default">
    <h1>My contract - <%= @contract.product.name %></h1>
  </div>
</div>

<div class="container">
  <div class="insurance-card" style="padding-top: 20px; padding-left: 20px; padding-right: 20px; padding-bottom: 20px">
    <div class="row">
      <div class="col-3">
        <div class="logo">
          <%= cl_image_tag @contract.company.logo.key, class:"insurance-logo", style: "width: 100%; background: white; padding:5px" %>
        </div>
      </div>
      <div class="col-5">
        <h1><strong><%= @contract.product.name %></strong></h1>
        <h2>Category: <strong><%= @contract.product.category.name %></strong></h2>
        <% if @contract.source === "work" %>
          <h2><strong><%= "No cost" %></strong></h2>
        <% elsif @contract.timing === "Monthly" %>
          <h2><%= @contract.price %> €/month</h2>
          <h2>Frequency: <%= @contract.timing %></h2>
        <% elsif @contract.timing === "Annually" %>
          <h2><%= @contract.price %> €/year</h2>
          <h2>Frequency: <strong><%= @contract.timing %></strong></h2>
        <% elsif ((@contract.ends_at.to_time.to_i - @contract.starts_at.to_time.to_i) / 3600 / 24) > 365 %>
          <h2><%= @contract.price %> € for <%= ((@contract.ends_at.to_time.to_i - @contract.starts_at.to_time.to_i) / 3600 / 24) / 365 %> year(s)</h2>
          <h2>Frequency: <strong><%= @contract.timing %></strong></h2>
        <% elsif ((@contract.ends_at.to_time.to_i - @contract.starts_at.to_time.to_i) / 3600 / 24) > 30 %>
          <h2><%= @contract.price %> € for <%= ((@contract.ends_at.to_time.to_i - @contract.starts_at.to_time.to_i) / 3600 / 24) / 30 %> month(s)</h2>
          <h2>Frequency: <strong><%= @contract.timing %></strong></h2>
        <% else %>
          <h2><%= @contract.price %> € for <%= ((@contract.ends_at.to_time.to_i - @contract.starts_at.to_time.to_i) / 3600 / 24) %> day(s)</h2>
          <h2>Frequency: <strong><%= @contract.timing %></strong></h2>
        <% end %>
        <h2>
          Contract pdf:
          <% if  @contract.pdf_contract.attached? %>
            <%= link_to @contract.pdf_contract.filename, rails_blob_path(@contract.pdf_contract, disposition: 'attachment') %>
          <% else %>
            <strong>N/A</strong>
            <h4 style="font-size: smaller"><i class="fa-solid fa-triangle-exclamation"></i>Warning no pdf contract, means no details.</h4>
          <% end %>
        </h2>
        <h2>
          Contract certificate:
          <% if  @contract.pdf_certificate.attached? %>
            <%= link_to @contract.pdf_certificate.filename, rails_blob_path(@contract.pdf_certificate, disposition: 'attachment') %>
          <% else %>
            <strong>N/A</strong>
          <% end %>
        </h2>
      </div>
      <div class="col-4">
        <div class="row">
          <div class="col-6 border-bottom pt-2">
            <h2>Status: </h2>
          </div>
          <div class="col-6 border-bottom pt-2 centered">
            <% if @contract.active %>
              <h3 class="rounded-border pink text-align-center"><strong>Active</strong></h3>
            <% else %>
              <h3 class="rounded-border gray"><strong>Inactive</strong></h3>
            <% end %>
          </div>
          <div class="col-6 border-bottom pt-2">
            <h2>Starts at:</h2>
          </div>
          <div class="col-6 border-bottom pt-2 centered">
            <h3><strong><%= @contract.starts_at.strftime('%d %b %Y') %></strong></h3>
          </div>
          <div class="col-6 border-bottom pt-2">
            <h2>Ends at:</h2>
          </div>
          <div class="col-6 border-bottom pt-2 centered">
            <h3><strong><%= @contract.ends_at&.strftime('%d %b %Y') %></strong></h3>
          </div>
          <div class="col-6 border-bottom pt-2">
            <h2>Contract source:</h2>
          </div>
          <div class="col-6 border-bottom pt-2 centered">
          <h3><strong><%= @contract.source.capitalize %></strong></h3>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <%# Accordion %>
    <h1 style="padding-top: 10px">What guarantees are you insured for?</h1>
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <% if @contract.pdf_contract.attached? %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
              Coverage 1
            </button>
          </h2>
          <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">Fire, electrical incident. Under your proof. In your temporary accommodation.</div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
              Coverage 2
            </button>
          </h2>
          <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">Unexpected collision with your home. In your possession during.</div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
              Coverage 3
            </button>
          </h2>
          <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">Damage due to a natural event. In your temporary accommodation rental.</div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-headingFour">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
              Coverage 4
            </button>
          </h2>
          <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">Burglary, vandalism and malicious damage. An assault with threats or brutality. In your garden or grounds</div>
          </div>
        </div>
      <% else %>
        <h4 style="font-size:smaller">Empty... if you want more detail, dowload your contract PDF <i class="fa-solid fa-otter"></i></h4>
        <%# End of Accordion %>
      <% end %>
    </div>
    <hr>
    <h1>Not convinced by your contract?</h1>

    <%= link_to "Edit Contract", edit_contract_path(@contract), class: "btn-gray"  %>
    <%= link_to "Delete Contract", contract_path(@contract), class: "btn-gray", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this contract?"} %>
  </div>
  <%# <div class="container"> %>
    <%= link_to "Back", contracts_path(category: @contract.product.category.name), class:"btn-gray", style:"width: 243px; margin-top: 20px;"%>
  <%# </div> %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kellizi, your insurance portfolio in your hands</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

     <!-- ===== Link Swiper's CSS ===== -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
     <!-- ===== Fontawesome CDN Link ===== -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"/>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="page-content">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/contact_us.html.erb
<div class="panel panel-default">
  <div class="container-fluid gradient">
    <div class="container panel-default">
      <h1>Contact us</h1>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="insurance-card p-2">
      <h1>How can we help?</h1>
      <h2>kellizi@gmail.com</h2>
      </div>
    </div>
  </div>
</div>

app/views/pages/user.html.erb
<h1> My profile </h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <h1>Kellizi <i class="fa-solid fa-otter"></i></h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <%# <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item dropdown">
            <i class="fa-solid fa-bars avatar p-2 fs-4 me-3" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "My profile", my_profile_path, class: "dropdown-item" %>
              <%= link_to "Contact us", contact_us_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <%# <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%# </li> %>
        <% end %>
      </ul>
    </div>
  </div>
</div>